<a href="https://colab.research.google.com/github/akankshakusf/Project-DeepLearning-SentimentAnalysis-DebertaHFT/blob/master/Sentiment_Analysis_with_BERT_in_HuggingFace.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Installation

In [ ]:
import os
os.environ['TF_USE_LEGACY_KERAS'] = '1'

In [ ]:
!pip install transformers==4.37.2 tensorflow==2.15.0

In [ ]:
!pip install tensorflow==2.15.0 --no-cache-dir --force-reinstall
!pip install tensorflow_text==2.15.0 --no-cache-dir --force-reinstall

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 156.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 475.3/475.3 MB 47.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 135.6/135.6 kB 80.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.5/57.5 kB 67.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.9/5.9 MB 61.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 61.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 26.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.5/24.5 MB 30.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 21.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.3/18.3 MB 59.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.9/71.9 kB 111.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 294.6/294.6 kB 192.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 20.5 MB/s eta 0:00:00
INFO: pip is looking at multiple versions of tf-keras to determine which version is compatible with other requirements. This could take a while.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 113.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 475.3/475.3 MB 250.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 135.6/135.6 kB 246.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.5/57.5 kB 209.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.9/5.9 MB 232.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 250.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 314.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.5/24.5 MB 146.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 210.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.3/18.3 MB 205.1

In [ ]:
!pip install  datasets #transformers

In [ ]:
# !pip install transformers==4.37.2
# !pip install keras==2.15.0
# !pip install tensorflow==2.15.0

In [ ]:
# TF_USE_LEGACY_KERAS=1

In [ ]:
# !pip uninstall keras -y
# !pip uninstall tensorflow -y

Found existing installation: tensorflow 2.18.0
Uninstalling tensorflow-2.18.0:
  Successfully uninstalled tensorflow-2.18.0


In [ ]:
import keras
print("Keras version:", keras.__version__)

import tensorflow as tf
print("TensorFlow version:", tf.__version__)
# Instead of tf.keras.__version__, use tf.__version__ to get the TensorFlow version,
# which includes Keras.
#Alternatively, if you need the standalone Keras version, use keras.__version__

import transformers
print("Transformers version:", transformers.__version__)

Keras version: 2.15.0
TensorFlow version: 2.15.1
Transformers version: 4.37.2


In [ ]:
# !pip install --upgrade tensorflow_text absl-py
# !pip install tensorflow_text==2.15.0 --force-reinstall --no-deps
# !pip install absl-py==1.4.0 --force-reinstall --no-deps

  Using cached tensorflow_text-2.19.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.0 kB)
  Using cached absl_py-2.2.2-py3-none-any.whl.metadata (2.6 kB)
  Using cached tensorflow-2.19.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.1 kB)
  Using cached tensorboard-2.19.0-py3-none-any.whl.metadata (1.8 kB)
  Using cached keras-3.9.2-py3-none-any.whl.metadata (6.1 kB)
  Using cached ml_dtypes-0.5.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (21 kB)
Using cached tensorflow_text-2.19.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.2 MB)
Using cached absl_py-2.2.2-py3-none-any.whl (135 kB)
Using cached tensorflow-2.19.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (644.9 MB)
Using cached keras-3.9.2-py3-none-any.whl (1.3 MB)
Using cached ml_dtypes-0.5.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.7 MB)
Using cached tensorboard-2.19.0-py3-none-any.whl (5.5 MB)
  Attempt

  Using cached tensorflow_text-2.15.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.9 kB)
Using cached tensorflow_text-2.15.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.2 MB)
  Attempting uninstall: tensorflow_text
    Found existing installation: tensorflow-text 2.19.0
    Uninstalling tensorflow-text-2.19.0:
      Successfully uninstalled tensorflow-text-2.19.0
  Using cached absl_py-1.4.0-py3-none-any.whl.metadata (2.3 kB)
Using cached absl_py-1.4.0-py3-none-any.whl (126 kB)
  Attempting uninstall: absl-py
    Found existing installation: absl-py 2.2.2
    Uninstalling absl-py-2.2.2:
      Successfully uninstalled absl-py-2.2.2


# Imports

In [29]:
#general package imports
import numpy as np
import matplotlib.pyplot as plt
import sklearn
import cv2
import seaborn as sns
import datetime
import pathlib
import io
import os
import re
import string
import time
from numpy import random
# import gensim.downloader as api
from PIL import Image

#tensorflow imports
import tensorflow as tf
import tensorflow_datasets as tfds
# import tensorflow_probability as tfp
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Layer
from tensorflow.keras.layers import Dense,Flatten,InputLayer,BatchNormalization,Dropout,Input,LayerNormalization
from tensorflow.keras.losses import BinaryCrossentropy,CategoricalCrossentropy, SparseCategoricalCrossentropy
from tensorflow.keras.metrics import Accuracy,TopKCategoricalAccuracy, CategoricalAccuracy, SparseCategoricalAccuracy
from tensorflow.keras.optimizers import Adam
from google.colab import drive
from google.colab import files
from datasets import load_dataset
from transformers import (BertTokenizerFast,TFBertTokenizer,BertTokenizer,RobertaTokenizerFast,
                          DataCollatorWithPadding,TFRobertaForSequenceClassification,TFBertForSequenceClassification,
                          TFBertModel,create_optimizer)

In [30]:
BATCH_SIZE=8

# Data Preparation for Bert Model

In [31]:
dataset_id = 'imdb'
dataset = load_dataset(dataset_id)

In [32]:
dataset

DatasetDict({
    train: Dataset({
        features: ['text', 'label'],
        num_rows: 25000
    })
    test: Dataset({
        features: ['text', 'label'],
        num_rows: 25000
    })
    unsupervised: Dataset({
        features: ['text', 'label'],
        num_rows: 50000
    })
})

In [33]:
dataset['train'][0:5] #any five texts

{'text': ['I rented I AM CURIOUS-YELLOW from my video store because of all the controversy that surrounded it when it was first released in 1967. I also heard that at first it was seized by U.S. customs if it ever tried to enter this country, therefore being a fan of films considered "controversial" I really had to see this for myself.<br /><br />The plot is centered around a young Swedish drama student named Lena who wants to learn everything she can about life. In particular she wants to focus her attentions to making some sort of documentary on what the average Swede thought about certain political issues such as the Vietnam War and race issues in the United States. In between asking politicians and ordinary denizens of Stockholm about their opinions on politics, she has sex with her drama teacher, classmates, and married men.<br /><br />What kills me about I AM CURIOUS-YELLOW is that 40 years ago, this was considered pornographic. Really, the sex and nudity scenes are few and far b

## Bert Model

In [34]:
#import tokenizer
model_id = "bert-base-uncased"
#initialize tokenizer model
tokenizer = BertTokenizerFast.from_pretrained(model_id)

In [35]:
tokenizer.is_fast

True

In [36]:
#test the tokenizer
test_input_1='The weather of today is Great! zwp'
test_input_2='How are you doing?'
inputs = [test_input_1, test_input_2]
tokenizer.tokenize(inputs,)

['the',
 'weather',
 'of',
 'today',
 'is',
 'great',
 '!',
 'z',
 '##w',
 '##p',
 'how',
 'are',
 'you',
 'doing',
 '?']

In [37]:
#instantiate tokenizer
output=tokenizer(inputs, padding=True, truncation=True,max_length=128)
print(output)

{'input_ids': [[101, 1996, 4633, 1997, 2651, 2003, 2307, 999, 1062, 2860, 2361, 102], [101, 2129, 2024, 2017, 2725, 1029, 102, 0, 0, 0, 0, 0]], 'token_type_ids': [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0]]}


In [38]:
#pull 0th element of list
tokenizer.decode(output['input_ids'][0])

'[CLS] the weather of today is great! zwp [SEP]'

In [39]:
#pull 1st element of list
tokenizer.decode(output['input_ids'][1])

'[CLS] how are you doing? [SEP] [PAD] [PAD] [PAD] [PAD] [PAD]'

In [40]:
def preprocess_function(examples):
  return tokenizer(examples["text"], padding=True,truncation=True,)

In [41]:
tokenized_dataset=dataset.map(preprocess_function,batched=True)

In [43]:
tokenized_dataset

DatasetDict({
    train: Dataset({
        features: ['text', 'label', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 25000
    })
    test: Dataset({
        features: ['text', 'label', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 25000
    })
    unsupervised: Dataset({
        features: ['text', 'label', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 50000
    })
})

In [ ]:
# tokenized_dataset['train'][0]

In [ ]:
#data_collector = DataCollatorWithPadding(tokenizer=tokenizer, return_tensors="tf")

In [44]:
tf_train_dataset = tokenized_dataset['train'].to_tf_dataset(
      columns= ['input_ids','token_type_ids','attention_mask','label'],
      shuffle=True,
      batch_size=BATCH_SIZE,
)

In [45]:
tf_val_dataset = tokenized_dataset['test'].to_tf_dataset(
    columns=['input_ids', 'token_type_ids', 'attention_mask', 'label'],
    shuffle = True,
    batch_size=BATCH_SIZE,
)

In [46]:
for i in tf_train_dataset.take(1):
  print(i)

{'label': <tf.Tensor: shape=(8,), dtype=int64, numpy=array([1, 0, 1, 0, 1, 1, 1, 0])>, 'input_ids': <tf.Tensor: shape=(8, 512), dtype=int64, numpy=
array([[ 101, 2023, 2143, ...,    0,    0,    0],
       [ 101, 1045, 3427, ...,    0,    0,    0],
       [ 101, 2204, 1010, ...,    0,    0,    0],
       ...,
       [ 101, 2383, 2657, ...,    0,    0,    0],
       [ 101, 1045, 2034, ...,    0,    0,    0],
       [ 101, 1999, 4369, ...,    0,    0,    0]])>, 'token_type_ids': <tf.Tensor: shape=(8, 512), dtype=int64, numpy=
array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])>, 'attention_mask': <tf.Tensor: shape=(8, 512), dtype=int64, numpy=
array([[1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       ...,
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0

In [108]:
# we will push labels back as it is outputs
def swap_postions(dataset):
  return{'input_ids':dataset['input_ids'],
         'token_type_ids':dataset['token_type_ids'],
         'attention_mask':dataset['attention_mask'],},dataset['label']

In [109]:
tf_train_dataset = tf_train_dataset.map(swap_postions).prefetch(tf.data.AUTOTUNE)
tf_val_dataset = tf_val_dataset.map(swap_postions).prefetch(tf.data.AUTOTUNE)

TypeError: in user code:


    TypeError: outer_factory.<locals>.inner_factory.<locals>.tf__swap_postions() takes 1 positional argument but 2 were given


In [49]:
for i in tf_train_dataset.take(1):
  print(i)

({'input_ids': <tf.Tensor: shape=(8, 512), dtype=int64, numpy=
array([[  101,  2044,  3752, ...,     0,     0,     0],
       [  101,  2417,  3239, ...,     0,     0,     0],
       [  101,  2515,  2505, ...,     0,     0,     0],
       ...,
       [  101, 18020,  3779, ...,     0,     0,     0],
       [  101,  9761, 11893, ...,     0,     0,     0],
       [  101,  2023,  2003, ...,     0,     0,     0]])>, 'token_type_ids': <tf.Tensor: shape=(8, 512), dtype=int64, numpy=
array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])>, 'attention_mask': <tf.Tensor: shape=(8, 512), dtype=int64, numpy=
array([[1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       ...,
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0]])>}, <tf.Tensor: shape=(8,), dtype=int64, nu

In [ ]:
tf_train_dataset

<_PrefetchDataset element_spec=({'input_ids': TensorSpec(shape=(None, 512), dtype=tf.int64, name=None), 'token_type_ids': TensorSpec(shape=(None, 512), dtype=tf.int64, name=None), 'attention_mask': TensorSpec(shape=(None, 512), dtype=tf.int64, name=None)}, TensorSpec(shape=(None,), dtype=tf.int64, name=None))>

In [ ]:
tf_val_dataset

<_PrefetchDataset element_spec=({'input_ids': TensorSpec(shape=(None, 512), dtype=tf.int64, name=None), 'token_type_ids': TensorSpec(shape=(None, 512), dtype=tf.int64, name=None), 'attention_mask': TensorSpec(shape=(None, 512), dtype=tf.int64, name=None)}, TensorSpec(shape=(None,), dtype=tf.int64, name=None))>

## Data Preparation for Roberta Model

In [109]:
model_id="roberta-base"
tokenizer=RobertaTokenizerFast.from_pretrained(model_id)

In [62]:
def preprocess_function(examples):
  return tokenizer(examples["text"],padding=True,truncation=True,)

In [110]:
tokenized_dataset = dataset.map(preprocess_function,)# batched=True)

In [64]:
tokenized_dataset['train'][0]

{'text': 'I rented I AM CURIOUS-YELLOW from my video store because of all the controversy that surrounded it when it was first released in 1967. I also heard that at first it was seized by U.S. customs if it ever tried to enter this country, therefore being a fan of films considered "controversial" I really had to see this for myself.<br /><br />The plot is centered around a young Swedish drama student named Lena who wants to learn everything she can about life. In particular she wants to focus her attentions to making some sort of documentary on what the average Swede thought about certain political issues such as the Vietnam War and race issues in the United States. In between asking politicians and ordinary denizens of Stockholm about their opinions on politics, she has sex with her drama teacher, classmates, and married men.<br /><br />What kills me about I AM CURIOUS-YELLOW is that 40 years ago, this was considered pornographic. Really, the sex and nudity scenes are few and far be

In [65]:
tokenized_dataset

DatasetDict({
    train: Dataset({
        features: ['text', 'label', 'input_ids', 'attention_mask'],
        num_rows: 25000
    })
    test: Dataset({
        features: ['text', 'label', 'input_ids', 'attention_mask'],
        num_rows: 25000
    })
    unsupervised: Dataset({
        features: ['text', 'label', 'input_ids', 'attention_mask'],
        num_rows: 50000
    })
})

In [89]:
# Instantiate the data collator
data_collator = DataCollatorWithPadding(tokenizer=tokenizer, return_tensors="tf")

In [101]:
tf_train_dataset = tokenized_dataset["train"].to_tf_dataset(
    columns=['input_ids','attention_mask', 'label'],
    shuffle=True,
    batch_size=BATCH_SIZE,
    collate_fn=data_collator
)

In [102]:
tf_val_dataset = tokenized_dataset["test"].to_tf_dataset(
    columns=['input_ids','attention_mask', 'label'],
    shuffle=True,
    batch_size=BATCH_SIZE,
    collate_fn=data_collator
)

In [105]:
# we will push labels back as it is outputs
def swap_positions(dataset):
  return{'input_ids':dataset['input_ids'],
         'attention_mask':dataset['attention_mask'],},dataset['labels']

In [106]:
tf_train_dataset=tf_train_dataset.map(swap_positions).prefetch(tf.data.AUTOTUNE)
tf_val_dataset=tf_val_dataset.map(swap_positions).prefetch(tf.data.AUTOTUNE)

In [107]:
for i in tf_train_dataset.take(1):
  print(i)

({'input_ids': <tf.Tensor: shape=(8, 499), dtype=int64, numpy=
array([[    0,   713,  1569, ...,     1,     1,     1],
       [    0,   713,    16, ...,     1,     1,     1],
       [    0, 21109,  1115, ...,    73,   698,     2],
       ...,
       [    0, 46255,  3369, ...,     1,     1,     1],
       [    0,  1121,   188, ...,     1,     1,     1],
       [    0, 14507, 31533, ...,     1,     1,     1]])>, 'attention_mask': <tf.Tensor: shape=(8, 499), dtype=int64, numpy=
array([[1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0]])>}, <tf.Tensor: shape=(8,), dtype=int64, numpy=array([0, 1, 0, 0, 1, 0, 1, 0])>)


# Modeling

## Based on TFBertForSequenceClassification

In [ ]:
#Instantiate the model
model= TFBertForSequenceClassification.from_pretrained("bert-base-uncased",num_labels=1)
model.summary()

All PyTorch model weights were used when initializing TFBertForSequenceClassification.

Some weights or buffers of the TF 2.0 model TFBertForSequenceClassification were not initialized from the PyTorch model and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


Model: "tf_bert_for_sequence_classification_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 bert (TFBertMainLayer)      multiple                  109482240 
                                                                 
 dropout_75 (Dropout)        multiple                  0 (unused)
                                                                 
 classifier (Dense)          multiple                  769       
                                                                 
Total params: 109483009 (417.64 MB)
Trainable params: 109483009 (417.64 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


## Custom BERT : Based on TFBertModel

In [50]:
model=TFBertModel.from_pretrained("bert-base-uncased")
model.summary()

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBertModel: ['cls.seq_relationship.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.weight', 'cls.predictions.bias']
- This IS expected if you are initializing TFBertModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFBertModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions w

Model: "tf_bert_model_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 bert (TFBertMainLayer)      multiple                  109482240 
                                                                 
Total params: 109482240 (417.64 MB)
Trainable params: 109482240 (417.64 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [51]:
input_ids=Input(shape = (512,),dtype=tf.int64,name='input_ids')
token_type_ids=Input(shape = (512,),dtype=tf.int64,name='token_type_ids')
attention_mask=Input(shape = (512,),dtype=tf.int64,name='attention_mask')

x = model([input_ids,token_type_ids,attention_mask])
print(x)
x=Dense(128,activation='relu')(x[0][:,0,:])
output=Dense(1,activation='sigmoid',name='label')(x)

custom_bert = tf.keras.Model(inputs=[input_ids,token_type_ids,attention_mask], outputs=output)

TFBaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=<KerasTensor: shape=(None, 512, 768) dtype=float32 (created by layer 'tf_bert_model_1')>, pooler_output=<KerasTensor: shape=(None, 768) dtype=float32 (created by layer 'tf_bert_model_1')>, past_key_values=None, hidden_states=None, attentions=None, cross_attentions=None)


In [52]:
custom_bert.summary()

Model: "model_1"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 input_ids (InputLayer)      [(None, 512)]                0         []                            
                                                                                                  
 token_type_ids (InputLayer  [(None, 512)]                0         []                            
 )                                                                                                
                                                                                                  
 attention_mask (InputLayer  [(None, 512)]                0         []                            
 )                                                                                                
                                                                                            

# Training

In [53]:
num_epochs = 3
batches_per_epoch = len(tokenized_dataset["train"])// BATCH_SIZE
total_train_steps = int(batches_per_epoch * num_epochs)

In [54]:
#import optimizer from hugging face
optimizer, schedule = create_optimizer(init_lr=2e-5,
                                       num_warmup_steps=0,
                                       num_train_steps=total_train_steps)

In [59]:
#compile the model
custom_bert.compile(loss=tf.keras.losses.BinaryCrossentropy(),
    optimizer=Adam(2e-5),
    metrics=['accuracy'],
    run_eagerly=True
)

In [60]:
#fit the model
history = custom_bert.fit(
    tf_train_dataset.take(1000),
    validation_data = tf_val_dataset,
    epochs = 3,
)

Epoch 1/3


   1/1000 [..............................] - ETA: 4:23:21 - loss: 0.7291 - accuracy: 0.6250

   2/1000 [..............................] - ETA: 4:09:15 - loss: 0.7392 - accuracy: 0.6250

   3/1000 [..............................] - ETA: 4:08:49 - loss: 0.6974 - accuracy: 0.6667

   4/1000 [..............................] - ETA: 4:09:34 - loss: 0.6862 - accuracy: 0.6250

   5/1000 [..............................] - ETA: 4:08:35 - loss: 0.6978 - accuracy: 0.5750

   6/1000 [..............................] - ETA: 4:07:32 - loss: 0.7077 - accuracy: 0.5417

   7/1000 [..............................] - ETA: 4:07:46 - loss: 0.7374 - accuracy: 0.5179

   8/1000 [..............................] - ETA: 4:10:50 - loss: 0.7832 - accuracy: 0.4844

   9/1000 [..............................] - ETA: 4:12:08 - loss: 0.7825 - accuracy: 0.4722

  10/1000 [..............................] - ETA: 4:11:01 - loss: 0.7859 - accuracy: 0.4625

  11/1000 [..............................] - ETA: 4:10:11 - loss: 0.7844 - accuracy: 0.4545

  12/1000 [..............................] - ETA: 4:09:26 - loss: 0.7752 - accuracy: 0.4583

  13/1000 [..............................] - ETA: 4:09:14 - loss: 0.7743 - accuracy: 0.4519

  14/1000 [..............................] - ETA: 4:08:54 - loss: 0.7683 - accuracy: 0.4643

  15/1000 [..............................] - ETA: 4:08:31 - loss: 0.7686 - accuracy: 0.4583

  16/1000 [..............................] - ETA: 4:08:18 - loss: 0.7645 - accuracy: 0.4609

  17/1000 [..............................] - ETA: 4:07:46 - loss: 0.7593 - accuracy: 0.4706

  18/1000 [..............................] - ETA: 4:07:18 - loss: 0.7520 - accuracy: 0.4792

  19/1000 [..............................] - ETA: 4:07:41 - loss: 0.7486 - accuracy: 0.4868

  20/1000 [..............................] - ETA: 4:07:14 - loss: 0.7335 - accuracy: 0.5063

  21/1000 [..............................] - ETA: 4:07:59 - loss: 0.7252 - accuracy: 0.5179

  22/1000 [..............................] - ETA: 4:07:35 - loss: 0.7327 - accuracy: 0.5114

  23/1000 [..............................] - ETA: 4:07:02 - loss: 0.7224 - accuracy: 0.5217

  24/1000 [..............................] - ETA: 4:06:31 - loss: 0.7342 - accuracy: 0.5156

  25/1000 [..............................] - ETA: 4:06:09 - loss: 0.7483 - accuracy: 0.5050

  26/1000 [..............................] - ETA: 4:05:26 - loss: 0.7427 - accuracy: 0.5096

KeyboardInterrupt: 

In [ ]:
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('model_loss')
plt.ylabel('loss')
plt.xlabel('epoch')
plt.legend(['train', 'val'], loc='upper left')
plt.show()

In [ ]:
plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])

plt.title('model_accuracy')
plt.ylabel('accuracy')
plt.xlabel('epoch')
plt.legend(['train', 'val'], loc='upper left')
plt.show()

# Testing

In [ ]:
inputs = tokenizer(["this movie looks very interesting, i love the fact that the actors do a great job in showing how people lived in the 18th century, which wasn't very good at all. But atleast this movie recreates this scenes! ",
                    "very good start, but movie started becoming uninteresting at some point though initially i thought it would have been much more fun. There was too much background noise, but later on towards the middle of the movie, my favorite character got in and he did a great job, so over "], padding=True,return_tensors="tf")

logits = model(**inputs).logits
print(logits)